# Introduction to pandas

Python module to work with tabular data (multidimensional), in the form of mainly **dataframes**. For extra tutorials [see here](https://pandas.pydata.org/pandas-docs/stable/getting_started/tutorials.html).

We start by loading the module and create a first dataframe filled with random values:


In [11]:
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.randn(8, 4), columns=['A', 'B', 'C', 'D'])
df

A         B         C         D
0 -0.042900  0.951714  1.523228 -0.733648
1 -0.498313  0.107837 -0.902923 -0.401364
2 -0.279902  0.611297  0.805298  0.212777
3  0.887346 -0.168621 -0.281563 -0.058242
4  0.915524 -1.238996  0.924851  1.347635
5  0.469548 -0.422438  0.641079 -1.119257
6  1.177346  0.736766  0.564312 -1.211992
7  1.083688  1.448752 -0.055297 -0.159039

A direct print results in a less formatted output:

In [3]:
print(df)

          A         B         C         D
0 -1.060869 -1.451677  1.167257  0.698541
1 -0.993398  0.404369 -1.941505 -0.182086
2  1.166057  0.642293 -1.199325 -0.233093
3  1.254090 -1.502589 -1.179849  0.300395
4 -0.342495 -0.719722  0.052097 -0.032500
5 -0.373821  1.664405  0.528887  3.337346
6  0.752104  0.598404  0.592797  0.045682
7  0.104658 -0.332441 -0.105034  1.060716


With the dataframe attribute ``.dtypes`` we can get the data type of each column in a Pandas dataframe:

In [5]:
df.dtypes

A    float64
B    float64
C    float64
D    float64
dtype: object

The dataframe method `head()` will show the first few rows of the dataframe; the attribute `.columns` returns the column names.

In [6]:
df.head()

A         B         C         D
0 -1.060869 -1.451677  1.167257  0.698541
1 -0.993398  0.404369 -1.941505 -0.182086
2  1.166057  0.642293 -1.199325 -0.233093
3  1.254090 -1.502589 -1.179849  0.300395
4 -0.342495 -0.719722  0.052097 -0.032500

In [7]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

With the method `to_numpy()` we convert a dataframe to an array; then we can slice it as we already saw for numpy arrays

In [8]:
arr = df.to_numpy()
print(arr)

[[-1.06086866 -1.45167741  1.16725665  0.69854081]
 [-0.99339839  0.40436886 -1.94150453 -0.18208624]
 [ 1.16605725  0.64229272 -1.19932493 -0.23309333]
 [ 1.25408998 -1.50258905 -1.17984899  0.30039515]
 [-0.34249535 -0.71972164  0.0520974  -0.03250014]
 [-0.37382111  1.66440531  0.52888739  3.3373459 ]
 [ 0.7521036   0.59840377  0.59279689  0.04568228]
 [ 0.10465815 -0.33244056 -0.10503392  1.06071625]]


In [9]:
arr[:,1] ## get second column

array([-1.45167741,  0.40436886,  0.64229272, -1.50258905, -0.71972164,
        1.66440531,  0.59840377, -0.33244056])

It is possible to create a data frame from a standard python dictionary, or from another dataframe

In [13]:
my_dict = {
    'name' : ['Annah', 'Giorgia', 'Luca'],
    'surname' : ['Montana', 'Smoth', 'Guerri'],
    'age' : [12, 20, 88]
}
df_from_dict = pd.DataFrame(my_dict)

df_from_dict

name  surname  age
0    Annah  Montana   12
1  Giorgia    Smoth   20
2     Luca   Guerri   88

In [14]:
df_from_df = pd.DataFrame(df_from_dict)
df_from_df

name  surname  age
0    Annah  Montana   12
1  Giorgia    Smoth   20
2     Luca   Guerri   88

# Slicing, in several ways

You can also slice directly the Pandas dataframe:

1. by column name

In [ ]:
df['A']

2. by slicing by rows

In [ ]:
df[0:2]

3a. by column names using the `.loc` syntax

In [12]:
print(df.loc[0:3, :])
df.loc[:, ['B','C']]

          A         B         C         D
0 -1.060869 -1.451677  1.167257  0.698541
1 -0.993398  0.404369 -1.941505 -0.182086
2  1.166057  0.642293 -1.199325 -0.233093
3  1.254090 -1.502589 -1.179849  0.300395


B         C
0 -1.451677  1.167257
1  0.404369 -1.941505
2  0.642293 -1.199325
3 -1.502589 -1.179849
4 -0.719722  0.052097
5  1.664405  0.528887
6  0.598404  0.592797
7 -0.332441 -0.105034

3b. by row names using the `.loc` syntax (passing through an index)

(see the doc for [.set_index()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.set_index.html) method for more details on setting indexes)

In [22]:
#adding a new column
df['Fruits'] = ['Apple', 'Banana', 'Coconut', 'Date', 'Elderberry', 'Fig', 'Grape', 'Juniper']

#setting the column as new index
df = df.set_index('Fruits')

#taking a look
df

A         B         C         D
Fruits                                            
Apple      -1.060869 -1.451677  1.167257  0.698541
Banana     -0.993398  0.404369 -1.941505 -0.182086
Coconut     1.166057  0.642293 -1.199325 -0.233093
Date        1.254090 -1.502589 -1.179849  0.300395
Elderberry -0.342495 -0.719722  0.052097 -0.032500
Fig        -0.373821  1.664405  0.528887  3.337346
Grape       0.752104  0.598404  0.592797  0.045682
Juniper     0.104658 -0.332441 -0.105034  1.060716

In [23]:
#extracting two rows
df.loc[['Apple', 'Banana'], :]

A         B         C         D
Fruits                                        
Apple  -1.060869 -1.451677  1.167257  0.698541
Banana -0.993398  0.404369 -1.941505 -0.182086

4. by position using the `.iloc` syntax (this is similar to numpy slicing)

In [24]:
df.iloc[0:2,2:4]

C         D
Fruits                    
Apple   1.167257  0.698541
Banana -1.941505 -0.182086

# Reading from a text file

It is possible to read a Pandas dataframe directly from a .csv file, either local or accessible from the web. We'll use the function [read_csv()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) which in its simplest form looks like this:

In [35]:
FILE_URL = 'https://raw.githubusercontent.com/ne1s0n/dataviz_python/main/resources/planets.csv'
planets = pd.read_csv(FILE_URL)

planets

Planet       Type  Mass (x ME)  Diameter (km)  Density (g/cm3)   Rotation  \
0  Mercury      Rocky       0.0553           4879            5.427   58.785 d   
1    Venus      Rocky       0.8150          12104            5.243  243.686 d   
2    Earth      Rocky       1.0000          12742            5.515  23.9345 h   
3     Mars      Rocky       0.1070           6779            3.933  24.6229 h   
4  Jupiter  Gas giant     317.8300         139822            1.326   9.9250 h   
5   Saturn  Gas giant      95.1590         116464            0.687   10.656 h   
6   Uranus  Gas giant      14.5360          50724            1.270    17.24 h   
7  Neptune  Gas giant      17.1470          49244            1.638    16.11 h   
8    Pluto      Rocky       0.0022           2376            1.854    6.405 d   

  Axis tilt (deg)  Magnetic field  Moons  \
0              ~0        0.000367      0   
1          177.36        0.000000      0   
2           23.44        1.000000      1   
3           25.19        0.000000      2   
4            3.13    18568.000000     80   
5           26.73      537.000000     83   
6           97.77       47.000000     27   
7           28.32       26.800000     14   
8          122.53        0.000000      5   

                                  Discovered  
0  Babilonian astronomers, 2nd millennium BC  
1  Babilonian astronomers, 2nd millennium BC  
2                                  Antiquity  
3  Babilonian astronomers, 2nd millennium BC  
4  Babilonian astronomers, 2nd millennium BC  
5  Babilonian astronomers, 2nd millennium BC  
6                             Herschel, 1781  
7                     Galle/Le Verrier, 1846  
8                             Tombaugh, 1930

Taking a look at the types we can discover a few interesting things. What happened to Rotation and Axis tilt?

In [5]:
planets.dtypes

Planet              object
Type                object
Mass ( x ME)       float64
Diameter (km)        int64
Density (g/cm3)    float64
Rotation            object
Axis tilt (deg)     object
Magnetic field     float64
Moons                int64
dtype: object

---

# ASSIGNMENT (reading csv)

Take a look at the documentation for [read_csv()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) to read the data again, but this time you'll need to: 

* specify that the column with the names of the planets needs to be used as index, so that we can then invoke something like `planets.loc['Venus', :]` 
* find a way to not read the last line, since Pluto is not a planet anymore :(

---

In [ ]:
# your solution here

## What about other formats?

There's several options, depending if you need to read:

* spreadsheet (excel, openoffice): use [read_excel()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html)
* xml: use [read_xml()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_xml.html)
* json (java script object notation): use [read_json()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_json.html)
* text, but fixed width: use [read_fwf()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_fwf.html)
* ... and many more

In general pandas is very well suited to import table-like pieces of data, so before writing your own import function take a look at what's available.

# Doing statistics on dataframes

A large number of methods compute descriptive statistics on dataframe. Most of these are aggregations like [sum()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sum.html), [mean()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.mean.html), but some of them, like [cumsum()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.cumsum.html), produce an object of the same size. 

Generally speaking, these methods take an axis argument, easily specified by an integer (axis=0 makes the operation go along the rows, axis=1 along the columns and so forth).

In [17]:
# a dataframe of random integers
df = pd.DataFrame(np.random.randint(100, size = (10, 4)), columns=['A', 'B', 'C', 'D'])
df

A   B   C   D
0   7  25  10  44
1  49  16  92  49
2  14  39  93  15
3  66  49  42  56
4  40   8  93  75
5  62  80  78   3
6  13  33  51   4
7  19  89  74  97
8  26  76  80  11
9  37  11  55  90

In [18]:
#mean - default is by column
df.mean()

A    33.3
B    42.6
C    66.8
D    44.4
dtype: float64

In [ ]:
#mean - specifying by row
df.mean(axis = 1)

In [ ]:
#can you guess what happens here?
df.mean(axis = 2)

In [23]:
#cumulative sum along the default axis
df.cumsum()

A    B    C    D
0    7   25   10   44
1   56   41  102   93
2   70   80  195  108
3  136  129  237  164
4  176  137  330  239
5  238  217  408  242
6  251  250  459  246
7  270  339  533  343
8  296  415  613  354
9  333  426  668  444

--- 

# ASSIGNMENT! (pandas replacement)

* create a pandas dataframe with 5 rows, 15 columns, and filled with random numbers between 1 and 10
* search the Pandas dataframe documentation for a method to replace all values equal to 8 with the number 888

---

In [ ]:
# your solution here

# Grouping

A very important pattern of operations when working with dataframes is grouping, also called "split-apply-combine". The idea is to split the dataframe rows depending on some value of the columns, and then apply some statistics operation on it. An example will clarify.

In [30]:
#the planets example
FILE_URL = 'https://raw.githubusercontent.com/ne1s0n/dataviz_python/main/resources/planets.csv'
planets = pd.read_csv(FILE_URL)

#focusing on just two columns, for simplicity
my_df = planets[['Type', 'Mass (x ME)' , 'Diameter (km)']]

#group by Type, compute the average of everything else
my_df.groupby('Type').mean()

Mass (x ME)  Diameter (km)
Type                                 
Gas giant     111.1680        89063.5
Rocky           0.3959         7776.0

The last command did several things:

* it split the dataframe in two groups using the values of the column "Type"
* it computed the required function (`.mean()`) on the split dataframe
* it recreated the index using the grouping column
* it returned a new dataframe. Notice that the original one is untouched

We could have avoided using the small `my_df` dataframe with a slightly more complex command:

In [34]:
#can you guess what's going on?
planets.groupby('Type')[['Mass (x ME)', 'Diameter (km)']].mean().reset_index()

Type  Mass (x ME)  Diameter (km)
0  Gas giant     111.1680        89063.5
1      Rocky       0.3959         7776.0

It's possible to easily group by more than one column:

In [36]:
planets.groupby(['Type', 'Discovered'])[['Mass (x ME)', 'Diameter (km)']].mean().reset_index()

Type                                 Discovered  Mass (x ME)  \
0  Gas giant  Babilonian astronomers, 2nd millennium BC   206.494500   
1  Gas giant                     Galle/Le Verrier, 1846    17.147000   
2  Gas giant                             Herschel, 1781    14.536000   
3      Rocky                                  Antiquity     1.000000   
4      Rocky  Babilonian astronomers, 2nd millennium BC     0.325767   
5      Rocky                             Tombaugh, 1930     0.002200   

   Diameter (km)  
0  128143.000000  
1   49244.000000  
2   50724.000000  
3   12742.000000  
4    7920.666667  
5    2376.000000

---

# ASSIGNMENT! (dataframe aggregate)

Count how many planets were discovered by babilonian astronomers using the `.groupby()` method

---

In [39]:
#your solution here

Discovered
Antiquity                                    1
Babilonian astronomers, 2nd millennium BC    5
Galle/Le Verrier, 1846                       1
Herschel, 1781                               1
Tombaugh, 1930                               1
Name: Planet, dtype: int64

# Out of the box descriptions

There's a couple of functions that produce a quick description of a dataframe and can be useful to make sense of the data. They are [.info()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html) and [.describe()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.describe.html)



In [40]:
planets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Planet           9 non-null      object 
 1   Type             9 non-null      object 
 2   Mass (x ME)      9 non-null      float64
 3   Diameter (km)    9 non-null      int64  
 4   Density (g/cm3)  9 non-null      float64
 5   Rotation         9 non-null      object 
 6   Axis tilt (deg)  9 non-null      object 
 7   Magnetic field   9 non-null      float64
 8   Moons            9 non-null      int64  
 9   Discovered       9 non-null      object 
dtypes: float64(3), int64(2), object(5)
memory usage: 848.0+ bytes


In [41]:
#aren'ts we missing something?
planets.describe()

Mass (x ME)  Diameter (km)  Density (g/cm3)  Magnetic field      Moons
count     9.000000       9.000000         9.000000        9.000000   9.000000
mean     49.627944   43903.777778         2.988111     2131.088930  23.555556
std     105.125961   51415.398474         2.013372     6166.320428  34.004085
min       0.002200    2376.000000         0.687000        0.000000   0.000000
25%       0.107000    6779.000000         1.326000        0.000000   1.000000
50%       1.000000   12742.000000         1.854000        1.000000   5.000000
75%      17.147000   50724.000000         5.243000       47.000000  27.000000
max     317.830000  139822.000000         5.515000    18568.000000  83.000000